### ISSUE TITLE
Aprimorar Relatorio1.md

### ISSUE THREAD

**Issue by fboldt** [fboldt/ProcessamentoDeSinaisBiologicos#2]
- [ ] Mudar o nome do arquivo para a "Base de Dados Sleep-EDF Database Expanded.md".
- [ ] Mudar nome do diretório Relatorios para relatorios (em letra minúscula).
- [ ] Mudar o título de "Relatório 1 - 14-09" para "Base de Dados Sleep-EDF Database Expanded".
- [ ] Colocar autor como parágrafo normal ou em itálico (sem ##).
- [ ] Alterar os níveis de subseções (###) para seções (##).
- [ ] Remover os espaços em branco (\&nbsp;).
- [ ] linha 7: Ressaltar -> ressaltar
- [ ] linha 37: frase muito grande. Dividir em mais frases.
- [ ] linha 39: resutando -> resultando
- [ ] linha 41: última frase muito extensa. Dividir.

**Comment by LucasRigo02** [comment]
aprimoramento finalizado, já criei o pull request com as modificações
